CREATE TABLE `aed_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device` int(11) NOT NULL,
  `owner` enum('Company','Government agency','Responder group','Sports group','Volunteer group','Other') NOT NULL,
  `access_code` text NOT NULL,
  `make` text NOT NULL,
  `model` text NOT NULL,
  `serial_number` text NOT NULL,
  `battery_expiry` date NOT NULL,
  `accessory_kit` tinyint(1) NOT NULL,
  `n_adult_pads` tinyint(4) NOT NULL,
  `adult_pad_expiry` date NOT NULL,
  `n_paediatric_pads` tinyint(4) NOT NULL,
  `paediatric_pad_expiry` date NOT NULL,
  `contact_name` text NOT NULL,
  `contact_number` tinytext,
  `contact_email` text,
  `post_address1` text,
  `post_address2` text,
  `post_address3` text,
  `eircode` text NOT NULL,
  `checked_by` text NOT NULL,
  `comments` text,
  `checked_at` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
